version: '3.8'

services:
  nginx:  # Service name and image name must be the same
    build: ./nginx  # Build from the custom Dockerfile inside "nginx" folder
    container_name: nginx
    ports:
      - '443:443'  # HTTPS only, assuming TLS is required
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/ssl  # Mount SSL certificates if needed
