version: '3.7'

services:
  # ----- Nginx ----- #
  nginx:
    build: ./srcs/requirements/nginx
    container_name: nginx
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ./srcs/requirements/nginx/conf.d:/etc/nginx/conf.d
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    restart: always
    networks:
      - inception-network

# ----- wordpress ----- #
  wordpress:
    build: ./srcs/requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis
    restart: always
    networks:
      - inception-network

  # ----- mariadb ----- #
  mariadb:
    build: ./srcs/requirements/mariadb
    container_name: mariadb
    ports:
      - '3306:3306'
    volumes:
      - wordpress_db_data:/var/lib/mysql
    env_file:
      - .env
    restart: always
    networks:
      - inception-network

  # ----- redis ----- #
  redis:
    build: srcs/requirements/bonus/redis
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    env_file:
      - .env
    restart: always
    networks:
      - inception-network
    
networks:
  inception-network:
    driver: bridge

volumes:
  wordpress_data:
  wordpress_db_data:
  redis_data:
