version: '3.8'

services:
  # ----- nginx -----
  nginx:
    build: ./src/nginx 
    container_name: nginx
    ports:
      - '443:443'
    volumes:
      - ./src/nginx/conf.d:/etc/nginx/conf.d
  # ----- nginx -----