version: '3.7'

services:
  # ----- Nginx -----
  nginx:
    build: ./srcs/requirements/nginx
    container_name: nginx
    ports:
      - '443:443'
    volumes:
      - ./srcs/requirements/nginx/conf.d:/etc/nginx/conf.d
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    restart: always
    networks:
      - inception-network
  # ----- Nginx -----

# ----- wordpress -----
  wordpress:
    build: ./srcs/requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    secrets:
      - db_password
      - wp_password
      - user_password
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception-network
  # ----- wordpress -----

  # ----- mariadb -----
  mariadb:
    build: ./srcs/requirements/mariadb
    container_name: mariadb
    ports:
      - '3306:3306'
    volumes:
      - wordpress_db_data:/var/lib/mysql
    env_file:
      - .env
    secrets:
      - db_password
    restart: always
    networks:
      - inception-network
  # ----- mariadb -----

networks:
  inception-network:
    driver: bridge

volumes:
  wordpress_data:
  wordpress_db_data:

secrets:
  db_password:
    file: ./secrets/db_password.txt
  wp_password:
    file: ./secrets/wp_password.txt
  user_password:
    file: ./secrets/user_password.txt