FROM debian:11

# Install vsftpd and necessary tools
RUN apt-get update && apt-get install -y vsftpd && rm -rf /var/lib/apt/lists/*

# Create an FTP user and set password
RUN useradd -m -d /home/ftpuser -s /bin/bash ftpuser && \
    echo "ftpuser:password" | chpasswd

COPY vsftpd.conf /etc/vsftpd.conf

# Allow FTP user to access the WordPress directory
RUN mkdir -p /var/www/wordpress && \
    chown -R ftpuser:ftpuser /var/www/wordpress

# Expose FTP ports
EXPOSE 20 21 30000-30010

CMD ["vsftpd", "/etc/vsftpd.conf"]
