FROM debian:11

RUN apt-get update && apt-get install -y vsftpd && rm -rf /var/lib/apt/lists/*

COPY vsftpd.conf /etc/vsftpd.conf

COPY ./tools/ftp.sh .

RUN chmod +x ftp.sh

EXPOSE 21

CMD ["./ftp.sh"]
